# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170220_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_size',
            field=models.CharField(choices=[('nagy', 'nagy'), ('kis', 'kis')], default='kis', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title_style',
            field=models.CharField(choices=[('kép_alatt_fekete', 'kép_alatt_fekete'), ('kép-alatt-sárga', 'kép-alatt-sárga'), ('kép-alatt-sima', 'kép-alatt-sima'), ('kép-felett-sárga', 'kép-felett-sárga'), ('képen-alul-sárga', 'képen-alul-sárga'), ('képen-felül-fekete', 'képen-felül-fekete')], default='kép_alatt_sárga', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to='pictures/', width_field='width_field'),
        ),
    ]
