# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headlines',
            field=models.BooleanField(default=False),
        ),
    ]
